export const exampleData = [
    {
        id: 1,
        type: "1x2",
        thumbnail: "/12.png",
        url: "22.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 2,
        type: "1x1",
        thumbnail: "/11.png",
        url: "22.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 3,
        type: "2x2",
        thumbnail: "/22.png",
        url: "/11.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 4,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 5,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 6,
        type: "1x2",
        thumbnail: "/12.png",
        url: "/11.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 7,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 8,
        type: "2x2",
        thumbnail: "/22.png",
        url: "/11.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 9,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 10,
        type: "1x2",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 11,
        type: "2x1",
        thumbnail: "/21.png",
        url: "/11.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 12,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 13,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 14,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 15,
        type: "2x1",
        thumbnail: "/21.png",
        url: "/22.png",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 16,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
    {
        id: 17,
        type: "1x1",
        thumbnail: "",
        url: "",
        titleEn: "test",
        titleZh: "test",
        captionEn: "test",
        captionZh: "test",
    },
];
